module.exports = {
  WORKFLOW_MODULE_ID: "wfm.workflow",
  WORKFLOW_DIRECTIVE_MODULE: "wfm.workflow.directives",
  WORKFLOWS_ENTITY_NAME: "workflows",
  WORKORDER_ENTITY_NAME: "workorders",
  WORKFLOW_UI_TOPIC_PREFIX: "wfm:ui",
  RESULTS_ENTITY_NAME: "results",
  SYNC_TOPIC_PREFIX: "wfm:sync",
  USERS_ENTITY_NAME: "users",
  STEPS_ENTITY_NAME: "step",
  WORKFLOW: "workflow",
  WORKFLOW_PREFIX: "wfm:workflows",
  TOPIC_TIMEOUT: 1000,
  TOPIC_PREFIX: "wfm",
  DONE_PREFIX: "done",
  ERROR_PREFIX: "error",
  TOPICS: {
    CREATE: "create",
    UPDATE: "update",
    LIST: "list",
    REMOVE: "remove",
    READ: "read",
    START: "start",
    STOP: "stop",
    FORCE_SYNC: "force_sync",
    SYNC_COMPLETE: "sync_complete",
    READ_PROFILE: "read_profile",
    SELECTED: "selected",
    BEGIN: "begin",
    SUMMARY: "summary",
    NEXT: "next",
    PREVIOUS: "previous",
    COMPLETE: "complete"
  },
  STATUS: {
    COMPLETE: "complete",
    COMPLETE_DISPLAY: "Complete",
    PENDING: "pending",
    PENDING_DISPLAY: "In Progress",
    NEW_DISPLAY: "New",
    UNASSIGNED_DISPLAY: "Unassigned"
  }
};